# Generated by Django 3.1 on 2020-09-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.FloatField()),
                ('workload', models.FloatField()),
                ('final_grade', models.IntegerField(default=None, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRS.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRS.student')),
            ],
        ),
    ]
