# Generated by Django 3.1 on 2020-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0002_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserating',
            name='semesters_taken',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
