# Generated by Django 3.1 on 2020-09-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRS', '0004_auto_20200907_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserating',
            name='student',
        ),
        migrations.AddField(
            model_name='courserating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courserating',
            name='final_grade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courserating',
            name='semesters_taken',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
