# Generated by Django 3.1 on 2020-10-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0008_auto_20201006_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='want_emails',
            field=models.IntegerField(default=1),
        ),
    ]
