# Generated by Django 3.1 on 2020-09-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0003_courserating_semesters_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_grade',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='credit_points',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
