# Generated by Django 3.1 on 2020-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0009_student_want_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='want_emails',
            field=models.BooleanField(default=True),
        ),
    ]
